### ISSUE TITLE
feat: 퀴즈 조회 기능 구현

### ISSUE THREAD

**Issue by Jeongjjuna** [FreakPeople/freak-CStar-backend#12]
## ✨ 어떤 기능인가요?
- 퀴즈 조회 기능 구현

## 📝 작업 상세 내용
- [ ] GET/v1/quizzes 에 해당하는 API 구현

**Comment by youjungHwang** [comment]
퀴즈 조회를 세부적으로 나눠 이슈 생성하도록 하겠습니다.
