### ISSUE TITLE
fix: 토큰 생성 버그 수정

### ISSUE THREAD

**Issue by Jeongjjuna** [FreakPeople/freak-CStar-backend#40]
## ❓ 어떤 버그인가요?
- jwt 토큰을 생성할때 subject에 email이 들어가지 않는 문제 

## 🤔 어떤 상황에서 발생한 버그인가요?
- jwt 토큰 생성 시 subject에 email이 들어가지 않았고(null), 그래서 filter의 인정과정에서 User객체에 email을 담아야 하는데 null값이 들어가게 되면서 에러가 발생.

## 🌈 예상 결과
- jwt 토큰을 인증 헤더로 전송하고, 검증하는 과정에서 jwt 토큰안에 subject에 존재하는 사용자 email이 principal email에 담겨야 한다.
- 즉, 인증과정에서 필터를 통과할 때 에러가 발생하지 않고 성공적으로 컨트롤러 계층에 도달해야함.

<img width="397" alt="image" src="https://github.com/user-attachments/assets/b52c3535-ec92-466b-bd03-22ef25b787a2">

위 사진에서 setClaims를 해버리면 subject가 덮어씌워져 버리기 때문에 addClaims로 바꿔줘야 합니다.
혹은 claims 변수에서 직접 subject를 설정하고, claims를 빌더에 넣어주는 방식으로 해결할 수 있습니다.

**Comment by youjungHwang** [comment]
가독성 좋게 하려고 위로 빼고 setClaims을 사용하였는데, 역시 알고 사용해야 할 것 같습니다! 다음에 해당부분 더 꼼꼼하게 확인하고 사용할게요!
